-- Mock Tests Table
-- Stores pre-generated mock tests for each exam (global, shared across all users)
CREATE TABLE IF NOT EXISTS mock_tests (
  id SERIAL PRIMARY KEY,
  exam_id INTEGER NOT NULL REFERENCES exams_taxonomies(id) ON DELETE CASCADE,
  mock_number INTEGER NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'generating'
    CHECK (status IN ('ready', 'generating', 'failed')),
  total_questions INTEGER DEFAULT 0,
  created_by VARCHAR(20) NOT NULL DEFAULT 'system'
    CHECK (created_by IN ('system', 'manual')),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  -- Unique constraint doubles as a generation lock: prevents duplicate mock creation
  UNIQUE(exam_id, mock_number)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_mock_tests_exam_id ON mock_tests(exam_id);
CREATE INDEX IF NOT EXISTS idx_mock_tests_exam_mock ON mock_tests(exam_id, mock_number);
CREATE INDEX IF NOT EXISTS idx_mock_tests_status ON mock_tests(status);

COMMENT ON TABLE mock_tests IS 'Pre-generated mock test batches per exam. Mock 1 is seeded manually; subsequent mocks are generated by background workers.';
COMMENT ON COLUMN mock_tests.exam_id IS 'Reference to exams_taxonomies';
COMMENT ON COLUMN mock_tests.mock_number IS 'Sequential mock number per exam (1, 2, 3, ...)';
COMMENT ON COLUMN mock_tests.status IS 'ready: questions available; generating: background job running; failed: generation failed';
COMMENT ON COLUMN mock_tests.total_questions IS 'Number of questions in this mock test';
COMMENT ON COLUMN mock_tests.created_by IS 'system: auto-generated by worker; manual: seeded manually';
