// Shared slot-fillers used by the template generator (src/generator.js).
// Keeping these in one place means every template automatically gets the same
// spread of situations, and adding a new context instantly multiplies every theme's pool.

const SLIDER_CONTEXTS = [
  "schoolwork",
  "a group project",
  "my friendships",
  "family decisions",
  "money and budgeting",
  "a new hobby",
  "sports or fitness",
  "social media",
  "exam preparation",
  "choosing a career path",
  "planning a trip",
  "a disagreement with a friend",
  "helping a younger sibling",
  "a club or society I'm part of",
  "an online discussion",
  "a deadline I'm racing against",
  "a competition I care about",
  "learning a new skill",
  "a tough conversation",
  "organizing an event",
  "a problem in my neighbourhood",
  "a new app or gadget",
  "a decision my parents are making",
  "a teacher's feedback",
  "a group chat",
  "a long-term goal",
  "a creative project",
  "a stressful situation",
  "meeting new people",
  "a sudden change of plans",
  "a tricky homework problem",
  "volunteering",
  "a part-time job or internship",
  "a game or puzzle",
  "public speaking",
  "a moral dilemma",
  "a friend's personal problem",
  "a class debate",
  "my daily routine",
  "a big life decision",
];

const SCENARIO_SETTINGS = [
  "during a school project",
  "on a family trip",
  "while organizing a club event",
  "in a group chat that's gone off track",
  "during a sports practice",
  "while planning a friend's birthday",
  "during a class debate",
  "while volunteering for a cause",
  "during exam season",
  "while working on a creative assignment",
  "during a college fair",
  "while helping with a community event",
  "during a group study session",
  "while on a school trip",
  "during a sudden schedule change",
  "while resolving a disagreement between friends",
  "during a part-time job or internship",
  "while learning something completely new",
  "during a competition you actually care about",
  "while mentoring a younger student",
  "during a family conversation about the future",
  "while dealing with an unexpected setback",
  "during a online collaboration with strangers",
  "while pitching an idea to your class",
  "during a long holiday with too much free time",
  "while fixing a problem no one else noticed",
  "during a tense group project deadline",
  "while organizing people for a cause you believe in",
  "during a one-on-one conversation with a teacher",
  "while figuring out what to do after a plan falls apart",
];

export { SLIDER_CONTEXTS, SCENARIO_SETTINGS };
