// Raw exam list (from "Exam sheet.csv" — 307 real Indian entrance exams/certifications).
// Each entry is classified into stream(s) and theme(s) by classifyExam() below,
// using keyword rules on the full exam name. This keeps the mapping maintainable —
// add a row here and it's auto-classified, no manual tagging needed.

const RAW_EXAMS = [
  ["ACCA FOUNDATION", "ACCA"],
  ["Actuarial Common Entrance Test", "ACET"],
  ["Advanced Industrial Training Institute Courses Admission", "AITI"],
  ["Air India Cadet Pilot Program", "AICPP"],
  ["Aligarh Muslim University Entrance Examination – Law", "AMU Law"],
  ["Aligarh Muslim University Undergraduate Entrance Test", "AMU UG"],
  ["All India Entrance Examination for Design – Interaction Design", "AIEED"],
  ["All India Law Entrance Test", "AILET"],
  ["All India Veterinary Entrance Test", "AIVET"],
  ["ALLIANCE UNIVERSITY ENTRANCE TEST", "AUSAT"],
  ["Amadeus GDS Certification Examination", "AGDS"],
  ["Amity University Entrance Examination", "AUEE"],
  ["Amrita Engineering Entrance Examination", "AEEE"],
  ["Anant National University Design Entrance Examination", "ANU DAT"],
  ["Andhra Pradesh Engineering and Agriculture and Pharmacy Common Entrance Test", "AP EAPCET"],
  ["Andhra Pradesh Law Common Entrance Test", "AP LAWCET"],
  ["Andhra Pradesh Polytechnic Entrance Examination", "AP POLYCET"],
  ["Apeejay Design Entrance Examination", "ADEE"],
  ["Armed Forces Medical College Entrance Examination", "AFMC"],
  ["Army Institute of Fashion and Design Entrance Examination", "AIFD"],
  ["Arunachal Pradesh Polytechnic Entrance Examination", "ARPEE-Poly"],
  ["Aryabhatta Knowledge University Entrance Examination", "AKU"],
  ["Ashoka University Aptitude and Aptitude Test – Interdisciplinary", "AAT"],
  ["Assam Agriculture Entrance Examination", "AAEE"],
  ["Assam Combined Entrance Examination", "ASSAM CEE"],
  ["Assam Polytechnic Entrance Examination", "ASPEE POLY"],
  ["Auxiliary Nurse Midwifery Admission", "ANM"],
  ["Avantika University Design Entrance Examination", "AUDEE"],
  ["AVEE - Assam Veterinary Entrance Examination", "AVEE"],
  ["Azim Premji University Undergraduate Entrance Examination", "APUUGEE"],
  ["Baba Farid University of Health Sciences Punjab Para Medical Entrance Test", "PPMET"],
  ["Bachelor of Business Administration in Aviation Admission", "BBAAA"],
  ["Bachelor of Science in Aviation Admission", "BSAA"],
  ["Bachelor of Science in Nautical Science Admission", "DNS / GP Rating"],
  ["Banaras Hindu University Undergraduate Entrance Test – Law", "BHU UET (Law)"],
  ["Bennett University Engineering Entrance Test", "BUMAT"],
  ["Bharati Vidyapeeth Common Entrance Test", "BVP CET"],
  ["Bihar Combined Entrance Competitive Examination", "BCECE"],
  ["Bihar Engineering Entrance Examination", "BEEE"],
  ["Bihar Polytechnic Common Entrance Competitive Examination", "BCECE PPE"],
  ["Bihar Sanskrit Studies Entrance", "BSEE"],
  ["Birla Institute of Technology and Science Admission Test", "BITSAT"],
  ["Birla Institute of Technology Mesra Entrance Examination", "BIT Mesra"],
  ["Cabin Crew Training Programme Admission", "CCTPA"],
  ["Central Sanskrit University Entrance Examination – Sanskrit Studies", "CSUEE SS"],
  ["Central Teacher Eligibility Test", "CTET"],
  ["Chandigarh Polytechnic Entrance", "CPE"],
  ["Chandigarh University Common Entrance Test", "CUCET"],
  ["Chandigarh University Common Entrance Test – Engineering", "CUCET Engineering"],
  ["Chartered Accountancy Final Examination", "CA Final"],
  ["Chartered Accountancy Foundation Examination", "CA Foundation"],
  ["Chartered Accountancy Intermediate Examination", "CA Intermediate"],
  ["Chennai Mathematical Institute Entrance Examination", "CMI Entrance"],
  ["Chattisgarh Pre-Agriculture Test", "CG PAT"],
  ["Chhattisgarh Pre Engineering Test", "CG PET"],
  ["Chhattisgarh Pre Pharmacy and Health Sciences Test", "CG PPHT"],
  ["Chhattisgarh Pre Polytechnic Test", "CG PPT"],
  ["Chhattisgarh Sanskrit Studies Entrance", "CHSEE"],
  ["Christ University Entrance Examination", "CUET (Christ)"],
  ["Christ University Law Entrance Examination", "CULEE"],
  ["Cochin University of Science and Technology Combined Admission Test – Marine Engineering", "CUSAT CAT"],
  ["College of Art Chandigarh Entrance Examination", "COA CEE"],
  ["Common Design Entrance Examination", "CDAC"],
  ["Common Law Admission Test – Undergraduate", "CLAT"],
  ["Common University Entrance Test – Undergraduate", "CUET"],
  ["Company Secretary Executive Entrance Test", "CS Executive"],
  ["Consortium of Medical Engineering and Dental Colleges of Karnataka Undergraduate Entrance Test", "COMEDK UGET"],
  ["Cost Management Accountancy Foundation Examination", "CMA Foundation"],
  ["Craft Instructor Training Scheme Admission", "CITS"],
  ["DAIICT Entrance Test", "DAIICT"],
  ["Defence Institute of Advanced Technology Entrance Examination", "DIAT"],
  ["Delhi College of Art Entrance Examination", "DCAEE"],
  ["Delhi Common Entrance Test", "Delhi CET"],
  ["Diploma in Aviation Admission", "DAA"],
  ["Dual System Training Admission", "DST"],
  ["English and Foreign Languages University Entrance Examination – Pashto and Persian", "EFLU"],
  ["FLAME University Entrance Examination", "FUEE"],
  ["Footwear Design and Development Institute All India Selection Test", "FDDI AIST"],
  ["Frankfinn Institute of Air Hostess Training Entrance Test", "FIAHTEE"],
  ["Galgotias University Entrance Test", "GSAT"],
  ["Galileo Global Distribution System Certification Examination", "GGDSCE"],
  ["General Nursing and Midwifery Admission", "GNM"],
  ["General Purpose Rating Course Admission", "GP Rating"],
  ["GLS University Design Entrance Examination", "GLSDEE"],
  ["Goa Common Entrance Test", "GCET"],
  ["Goa Common Entrance Test – Engineering", "GCET Engineering"],
  ["Goa Polytechnic Entrance Examination", "GPEE"],
  ["Graphic Era University Entrance Test", "GEEE"],
  ["Gujarat Common Entrance Test", "GUJCET"],
  ["Gujarat Common Entrance Test – Medical and Pharmacy", "GUJCET Med"],
  ["Gujarat Common Entrance Test – Polytechnic", "GUJCET / ACPC"],
  ["Guru Gobind Singh Indraprastha University Common Entrance Test", "IPU CET"],
  ["Guru Gobind Singh Indraprastha University Common Entrance Test for Bachelor of Hotel Management and Catering Technology", "GGSIUCETBHMCT"],
  ["Guru Gobind Singh Indraprastha University Common Entrance Test for Bachelor of Journalism and Mass Communication", "GGSIUCETBJMC"],
  ["Haryana Agriculture Entrance Examination", "HAEE"],
  ["Haryana Bachelor of Arts Entrance Examination", "HBAEE"],
  ["Haryana Bachelor of Business Administration Admission", "HBBAA"],
  ["Himachal Pradesh Bachelor of Arts Entrance Examination", "HPBAEE"],
  ["Himachal Pradesh Bachelor of Business Administration Admission", "HPBBAA"],
  ["Himachal Pradesh Common Entrance Test", "HPCET"],
  ["Himachal Pradesh Polytechnic Admission Test", "HPPAT"],
  ["ICFAI Technology School Admission Test", "ICFAITSAT"],
  ["IMS Design and Innovation Academy Entrance Examination", "IMSDIAEE"],
  ["Indian Council of Agricultural Research All India Entrance Examination for Admission Undergraduate", "ICARAIEEAU"],
  ["Indian Institute of Art and Design Entrance Test", "IIADET"],
  ["Indian Institute of Foreign Trade Entrance Examination", "IIFTEE"],
  ["Indian Institute of Petroleum and Energy Entrance Examination", "IIPEEE"],
  ["Indian Institute of Science Bachelor of Science Research Admission", "IISBSRA"],
  ["Indian Institute of Space Science and Technology Admission", "IISSTA"],
  ["Indian Institutes of Science Education and Research Aptitude Test", "IISERAT"],
  ["Indian Maritime University Common Entrance Test", "IMUCET"],
  ["Indira Gandhi Rashtriya Uran Akademi Entrance Examination", "IGRUAEE"],
  ["Indira Kala Sangeet University Entrance", "IKSUE"],
  ["Industrial Training Institute Admission National Council for Vocational Training", "ITIANCVT"],
  ["Industrial Training Institute Admission State Council for Vocational Training", "ITIASCVT"],
  ["Industrial Training Institute Trades Admission", "ITITA"],
  ["Institute of Hotel Management Aurangabad Entrance Test", "IHMAET"],
  ["National Council for Hotel Management and Catering Technology Joint Entrance Examination", "NCHMCT JEE"],
  ["Integrated Bachelor of Arts and Bachelor of Education Entrance Examination", "IBABEEE"],
  ["Inter National Institute of Fashion Design Entrance Examination", "INIFDEE"],
  ["International Air Transport Association Certification", "IATAC"],
  ["International Institute of Hotel Management Electronic Common Hospitality Admission Test", "IIHMECHAT"],
  ["ITM Design Entrance Examination", "ITMDEE"],
  ["Jain Entrance Test", "JET"],
  ["Jamia Millia Islamia Engineering Entrance Examination", "JMIEEE"],
  ["Jamia Millia Islamia Mass Communication Entrance", "JMIMCE"],
  ["Jammu and Kashmir Bachelor of Business Administration Admission", "JKBBAA"],
  ["Jawaharlal Institute of Postgraduate Medical Education and Research Nursing Entrance Examination", "JIPMERNEE"],
  ["JD Institute of Fashion Technology Design Entrance Examination", "JDIFTDEE"],
  ["Jharkhand Bachelor of Business Administration Admission", "JBBAA"],
  ["Jharkhand Combined Entrance Competitive Examination", "JCECE"],
  ["Jharkhand Combined Entrance Competitive Examination Pre Polytechnic Test", "JCECEPPT"],
  ["JK Lakshmipat University Design Entrance Examination", "JKLUDEE"],
  ["Joint Entrance Examination", "JEE"],
  ["Joint Entrance Examination Council Uttar Pradesh Polytechnic Entrance Examination", "JEECUPPEE"],
  ["Joint Entrance Test Agriculture", "JETA"],
  ["Joint Integrated Programme in Management Admission Test", "JIPMAT"],
  ["K. R. Mangalam University Entrance Test", "KRMUET"],
  ["Kalinga Institute of Industrial Technology Entrance Examination Management Undergraduate", "KIITEEMU"],
  ["Karnataka Bachelor of Business Administration Entrance Examination", "KBBAEE"],
  ["Karnataka Chitrakala Parishath Entrance", "KCPE"],
  ["Karnataka Common Entrance Test", "KCET"],
  ["Kashmir Polytechnic Entrance", "KPE"],
  ["Kerala Dairy Technology Entrance", "KDTE"],
  ["Kerala Engineering Architecture Medical Entrance Examination", "KEAMEE2"],
  ["Kerala Fisheries Entrance Examination", "KFEE"],
  ["Kerala Food Technology Entrance", "KFTE"],
  ["Kerala Forestry Entrance Examination", "KFEE2"],
  ["Kerala Law Entrance Examination", "KLEE"],
  ["Kerala Nursing Entrance Examination", "KNEE"],
  ["Kerala Paramedical Entrance Examination", "KPEE"],
  ["Kerala Polytechnic Entrance Examination", "KPEE2"],
  ["Kerala Veterinary Entrance Examination", "KVEE"],
  ["Krea University Entrance", "KUE"],
  ["Krea University Liberal Arts Entrance Examination", "KULAEE"],
  ["Ladakh Bachelor of Business Administration Entrance Examination", "LBBAEE"],
  ["Lakshadweep Bachelor of Business Administration Entrance Examination", "LBBAEE2"],
  ["Law Aptitude Test", "LAT"],
  ["LISAA School of Design Entrance Test", "LISAASDET"],
  ["Lovely Professional University National Entrance and Scholarship Test", "LPUNEST"],
  ["Lovely Professional University National Entrance and Scholarship Test Design", "LPUNESTD"],
  ["Madhya Pradesh Bachelor of Arts Entrance Examination", "MPBAEE"],
  ["Madhya Pradesh Bachelor of Business Administration Entrance Examination", "MPBBAEE"],
  ["Madhya Pradesh Polytechnic Entrance Examination", "MPPEE"],
  ["Madhya Pradesh Pre Agriculture Test", "MPPAT"],
  ["Madhya Pradesh Pre Engineering Test", "MPPET"],
  ["Madhya Pradesh Pre Nursing Selection Test", "MPPNST"],
  ["Madhya Pradesh Pre Polytechnic Test", "MPPPT"],
  ["Madhya Pradesh Pre Veterinary and Fisheries Test", "MPPVFT"],
  ["Madras School Of Social Work Entrance", "MSSWE"],
  ["Maharaja Sayajirao University of Baroda Fine Arts Entrance Examination", "MSUBFAEE"],
  ["Maharashtra Bachelor of Science Nursing Common Entrance Test", "MBSNCET"],
  ["Maharashtra Common Entrance Test", "MCET"],
  ["Maharashtra Paramedical Common Entrance Test", "MPCET"],
  ["Maharashtra Polytechnic Entrance Examination", "MPEE"],
  ["Manipal Academy of Higher Education Design Entrance Examination", "MAHEDEE"],
  ["Manipal Entrance Test", "MET"],
  ["Manipal Media Entrance", "MME"],
  ["Manipur Bachelor of Business Administration Entrance Examination", "MBBAEE"],
  ["Manipur Polytechnic Entrance Examination", "MPEE2"],
  ["Meghalaya Bachelor of Business Administration Entrance Examination", "MBBAEE2"],
  ["Meghalaya Engineering Entrance Examination", "MEEE"],
  ["Meghalaya Polytechnic Entrance Examination", "MPEE3"],
  ["Military Nursing Service Entrance Examination", "MNSEE"],
  ["MIT Institute of Design Design Aptitude Test", "MITID DAT"],
  ["MIT World Peace University Entrance Test", "MITWPUET"],
  ["Mizoram Bachelor of Business Administration Entrance Examination", "MBBAEE3"],
  ["Mizoram Engineering Entrance Examination", "MEEE2"],
  ["Mizoram Polytechnic Entrance", "MPE"],
  ["Nagaland Engineering Entrance Examination", "NEEE"],
  ["Nagaland Polytechnic Entrance", "NPE"],
  ["Narsee Monjee Institute of Management Studies Law Aptitude Test", "NMIMSLAT"],
  ["Narsee Monjee Institute of Management Studies National Test for Programs After Twelfth", "NMIMS NPAT"],
  ["National Aptitude Test in Architecture", "NATA"],
  ["National Eligibility cum Entrance Test Undergraduate", "NEET"],
  ["National Entrance Screening Test", "NEST"],
  ["National Forensic Sciences University Forensic Science Entrance Examination", "NFSUFSEE"],
  ["National Institute of Design Design Aptitude Test Toy Design", "NIDDATTD"],
  ["National Institute of Fashion Technology Entrance Examination", "NIFTEE"],
  ["National Institute of Mental Health and Neuro Sciences Bachelor of Science Neurophysiology Entrance Examination", "NIMHNSBSNEE"],
  ["National Rail and Transportation Institute Admission Test", "NRTI Test"],
  ["National Standard Examination", "NSE"],
  ["North Eastern Indira Gandhi Regional Institute of Health and Medical Sciences Bachelor of Science Nursing Entrance Examination", "NEIGRIHMSBSNEE"],
  ["O. P. Jindal Global University Entrance Test", "OPJGUET"],
  ["Oberoi Systematic Training and Education Programme", "OSTEP"],
  ["Odisha Diploma Entrance Test", "ODET"],
  ["Odisha Joint Entrance Examination", "OJEE"],
  ["Odisha Joint Entrance Examination Agriculture", "OJEEA"],
  ["Odisha Polytechnic Entrance Examination", "OPEE"],
  ["Odisha University of Agriculture and Technology Entrance Examination", "OUATEE"],
  ["Online Facilitation System for Students Bihar University Admission", "OFSSBUA"],
  ["Panjab University Design Entrance Examination", "PUDEE"],
  ["Panjab University Undergraduate Law Entrance Test", "PUULET"],
  ["Paramedical State Common Entrance Test", "PSCET"],
  ["Parul University Entrance Test", "PUET"],
  ["Pearl Academy Entrance Examination", "PAEE"],
  ["PES Scholastic Aptitude Test", "PESSAT"],
  ["Plaksha University Undergraduate Tech Entrance Test", "PUUTET"],
  ["Pradhan Mantri Kaushal Vikas Yojana", "PMKVY"],
  ["Presidency University Bachelor Degree Entrance Test", "PUBDET"],
  ["Presidency University Entrance Test", "PUET2"],
  ["Puducherry Bachelor of Business Administration Entrance Examination", "PBBAEE"],
  ["Puducherry Polytechnic Entrance", "PPE"],
  ["Punjab Bachelor of Business Administration Entrance Examination", "PBBAEE2"],
  ["PJET (Punjab Joint Entrance Test)", "PJET"],
  ["Punjab Para Medical Entrance Test Baba Farid University of Health Sciences", "PPMETBFUHS"],
  ["Punjab State Board of Technical Education Polytechnic Admission Test", "PSBTEPAT"],
  ["Rabindra Bharati University Entrance", "RBUE"],
  ["Raffles Design Entrance Examination", "RDEE"],
  ["Rajasthan Bachelor of Business Administration Entrance Examination", "RBBAEE"],
  ["Rajasthan Engineering Admission Process", "REAP"],
  ["Rajasthan Polytechnic Entrance Examination", "RPEE"],
  ["Rajasthan Pre-Diploma in Elementary Education Entrance Examination", "Rajasthan Pre D.El.Ed/BSTC"],
  ["Rajasthan Pre Veterinary Test", "RPVT"],
  ["Rajasthan University Law Entrance Test", "RULET"],
  ["Rajasthan University of Health Sciences Bachelor of Science Nursing Entrance Examination", "RUHSBSNEE"],
  ["Rajasthan University of Health Sciences Entrance Examination", "RUHS CET"],
  ["Rajasthan University of Health Sciences Paramedical Entrance Examination", "RUHSPEE"],
  ["Rajiv Gandhi Institute of Petroleum Technology Bachelor of Technology Entrance Examination", "RGIPTBTEE"],
  ["Rashtriya Raksha University (Police)", "RRUP"],
  ["REVA University Entrance Test", "REVAUET"],
  ["School of Fashion India Entrance Test", "SFIET"],
  ["School of Fashion Technology Entrance Test", "SFTET"],
  ["Sharda University Admission Test", "SUAT"],
  ["Shiv Nadar University Entrance Test", "SNUET"],
  ["Shiv Nadar University Management Aptitude Test and Entrance Examination", "SNUMATEE"],
  ["Shiv Nadar University Scholastic Aptitude Test", "SNUSAT"],
  ["Sikkim Bachelor of Business Administration Entrance Examination", "SBBAEE"],
  ["Sikkim Manipal University Design Entrance Examination", "SMUDEE"],
  ["Sikkim Manipal University Entrance Test", "SMUET"],
  ["Sikkim Polytechnic Entrance Examination", "SPEE"],
  ["Sir Jamsetjee Jeejebhoy School of Art Entrance Examination", "SJJSAEE"],
  ["Somaiya Design Entrance Examination", "SDEE"],
  ["Srishti Manipal (Design)", "SMD"],
  ["SRM Joint Engineering Entrance Examination", "SRMJEEE"],
  ["St Joseph's University Entrance Examination", "SJSUEE"],
  ["St Xavier's College Entrance Examination", "SXSCEE"],
  ["State Teacher Eligibility Tests", "STET"],
  ["Swami Vivekananda Yoga Anusandhana Samsthana Bachelor of Science Yoga Entrance Examination", "SVYASBSYEE"],
  ["Symbiosis Entrance Test", "SET"],
  ["Symbiosis Institute of Design Entrance Test", "SIDET"],
  ["Symbiosis Institute Of Media Entrance", "SIME"],
  ["Symbiosis Institute of Technology Engineering Entrance Examination", "SITEEE"],
  ["Symbiosis Law Admission Test", "SLAT"],
  ["Symbiosis Liberal Arts Entrance", "SLAE"],
  ["Tamil Nadu Bachelor of Business Administration Entrance Examination", "TNBBAEE"],
  ["Tamil Nadu Dr Ambedkar Law University Entrance Test", "TNDALUET"],
  ["Tamil Nadu Engineering Admissions", "TNEA"],
  ["Tamil Nadu Polytechnic Entrance Examination", "TNPEE"],
  ["Tata Institute of Social Sciences Bachelor Admission Test", "TISSBAT"],
  ["Tata Institute of Social Sciences Bachelor of Vocation Agriculture Entrance Examination", "TISSBVAEE"],
  ["Telangana Engineering Agriculture and Pharmacy Common Entrance Test Biology Physics Chemistry Stream", "TEAPCETBPCS"],
  ["Telangana Law Common Entrance Test", "TLCET"],
  ["Telangana State Engineering Agriculture and Medical Common Entrance Test", "TSEAMCET"],
  ["Telangana State Polytechnic Common Entrance Test", "TSPCET"],
  ["The Design Village Entrance Test", "DVET"],
  ["Tripura Board of Joint Entrance Examination", "TBJEE"],
  ["Tripura Polytechnic Entrance Examination", "TPEE"],
  ["Undergraduate Common Entrance Examination for Design", "UCEED"],
  ["Unitedworld Institute of Design Entrance Examination", "UIDEE"],
  ["University of Petroleum and Energy Studies Design Entrance Examination", "UPESDEE"],
  ["University of Petroleum and Energy Studies Disaster Management Entrance Examination", "UPESDMEE"],
  ["University of Petroleum and Energy Studies Engineering Aptitude Test", "UPESEAT"],
  ["University of Petroleum and Energy Studies Entrance Test", "UPESET"],
  ["Uttar Pradesh Combined Agriculture and Technology Entrance Test", "UPCATET"],
  ["Uttar Pradesh Combined Paramedical Entrance Test", "UPCPET"],
  ["Uttar Pradesh Common Nursing Entrance Test", "UPCNET"],
  ["Uttar Pradesh Paramedical Entrance Test", "UPPET"],
  ["Uttar Pradesh State Entrance Examination Abdul Kalam Technical University", "UPSEEAKTU"],
  ["Uttar Pradesh State Entrance Examination Bachelor of Hotel Management and Catering Technology", "UPSEEBHMCT"],
  ["Uttarakhand Joint Entrance Examination Polytechnic", "UJEEP"],
  ["Uttarakhand Nursing Entrance Exam", "UNEE"],
  ["Uttarakhand Paramedical Entrance Exam", "UPEE"],
  ["Uttarakhand State Entrance Examination", "USEE"],
  ["Vellore Institute of Technology Design Entrance Examination", "VITDEE"],
  ["Vellore Institute of Technology Engineering Entrance Examination", "VITEEE"],
  ["Vogue Institute of Art and Design Entrance Examination", "VIADEE"],
  ["Vogue University Design Entrance Examination", "VUDEE"],
  ["West Bengal Bachelor of Arts Admission", "WBBAA"],
  ["West Bengal Joint Entrance Examination", "WBJEE"],
  ["West Bengal Joint Entrance Test for Nursing, Paramedical and Allied Sciences Undergraduate", "JENPAS UG"],
  ["West Bengal Paramedical Entrance Test", "WBPET"],
  ["Whistling Woods International Design Entrance Examination", "WWIDEE"],
  ["World University of Design Aptitude Test Visual Arts", "WUDATVA"],
  ["World University of Design Entrance Test", "WUDET"],
];

// Keyword -> stream/theme rules, checked in order, first matches win (multiple rules can add to the same exam).
const STREAM_RULES = [
  [/law|legal|judic/i, ["Humanities", "Commerce"]],
  [/design|fashion|fine arts?|art\b|visual arts|toy design/i, ["PCMB", "Humanities"]],
  [/medic|nursing|veterinary|neet|pharmac|dental|paramedic|forensic|nutrition|yoga|physiotherapy|midwifery|health sciences|neuro|afmc/i, ["PCB", "PCMB"]],
  [/engineering|polytechnic|\bjee\b|architecture|nata|technology|tech\b|vit|bitsat|srmjeee|comedk|wbjee|cusat|petroleum|maritime|space|defence institute|forensic/i, ["PCM"]],
  [/agricultur|forestry|fisheries|dairy|veterinary/i, ["PCB", "Vocational"]],
  [/business administration|\bbba\b|management|commerce|chartered accountancy|\bca \b|company secretary|cost management|actuarial|hotel|aviation|cabin crew|hospitality|air hostess|gds|iata/i, ["Commerce"]],
  [/teacher eligibility|\btet\b|liberal arts|social work|mass communication|journalism|sanskrit|media|bachelor of arts|interdisciplinary/i, ["Humanities"]],
  [/\biti\b|vocational|craft instructor|dual system|kaushal vikas|rating\b|nautical|polytechnic|diploma/i, ["Vocational"]],
];

const THEME_RULES = [
  [/law|legal|judic/i, ["storyteller", "chessplayer", "collector", "conviction"]],
  [/design|fashion|fine arts?|art\b|visual arts|toy design/i, ["ideaspark", "visionary", "collector", "amplifier"]],
  [/medic|nursing|veterinary|neet|pharmac|dental|paramedic|nutrition|yoga|physiotherapy|midwifery|health sciences|neuro|afmc/i, ["heartreader", "ownership", "conviction", "growthseeker"]],
  [/engineering|polytechnic|\bjee\b|architecture|nata|technology|tech\b|vit|bitsat|srmjeee|comedk|wbjee|cusat|petroleum|maritime|space|defence institute/i, ["evidence", "laser", "structure", "chessplayer"]],
  [/agricultur|forestry|fisheries|dairy/i, ["fixer", "ownership", "growthseeker"]],
  [/business administration|\bbba\b|management|commerce|chartered accountancy|\bca \b|company secretary|cost management|actuarial/i, ["stageowner", "igniter", "amplifier", "chessplayer"]],
  [/hotel|aviation|cabin crew|hospitality|air hostess|gds|iata/i, ["connector", "welcomeall", "flowstate"]],
  [/teacher eligibility|\btet\b/i, ["grower", "heartreader", "storyteller"]],
  [/liberal arts|social work|mass communication|journalism|media/i, ["storyteller", "heartreader", "ideaspark"]],
  [/sanskrit|bachelor of arts|interdisciplinary/i, ["deepthink", "collector", "growthseeker"]],
  [/forensic/i, ["evidence", "deepthink", "conviction"]],
  [/\biti\b|vocational|craft instructor|dual system|kaushal vikas|rating\b|nautical|diploma/i, ["fixer", "structure", "flowstate"]],
];

// Field categories shown as colored exam boxes in the report. Checked in order,
// first match wins (unlike stream/theme rules, an exam only gets ONE category).
const CATEGORY_RULES = [
  ["Design", /design|fashion|fine arts?|\bart\b|visual arts|toy design/i, "#db2777"],
  ["Law", /law|legal|judic/i, "#b45309"],
  ["Medical", /medic|nursing|veterinary|neet|pharmac|dental|paramedic|nutrition|yoga|physiotherapy|midwifery|health sciences|neuro|afmc/i, "#dc2626"],
  ["Defence", /defence|nda\b|naval|military|police|rashtriya raksha/i, "#475569"],
  ["Agriculture", /agricultur|forestry|fisheries|dairy/i, "#65a30d"],
  ["Hospitality & Aviation", /hotel|aviation|cabin crew|hospitality|air hostess|gds|iata|nautical|maritime/i, "#0891b2"],
  ["Media & Communication", /mass communication|journalism|media\b/i, "#c026d3"],
  ["Teaching & Education", /teacher eligibility|\btet\b/i, "#7c3aed"],
  ["Engineering", /engineering|polytechnic|\bjee\b|architecture|nata|technology|tech\b|vit|bitsat|srmjeee|comedk|wbjee|cusat|petroleum|space|defence institute/i, "#2563eb"],
  ["Management & Commerce", /business administration|\bbba\b|management|commerce|chartered accountancy|\bca \b|company secretary|cost management|actuarial/i, "#059669"],
  ["Vocational", /\biti\b|vocational|craft instructor|dual system|kaushal vikas|rating\b|diploma/i, "#ea580c"],
];

function categoryFor(name) {
  for (const [category, re, color] of CATEGORY_RULES) {
    if (re.test(name)) return { category, color };
  }
  return { category: "General", color: "#6b7280" };
}

// Placeholder link until the website CMS supplies real official exam URLs —
// keeps the `url` field name stable so swapping in real links later is a
// one-line change in classifyExam(), no UI changes needed.
function examSearchUrl(name, abbr) {
  return `https://www.google.com/search?q=${encodeURIComponent(`${abbr} ${name} official website`)}`;
}

function classifyExam([name, abbr]) {
  const streams = new Set();
  const themes = new Set();
  for (const [re, vals] of STREAM_RULES) {
    if (re.test(name)) vals.forEach((v) => streams.add(v));
  }
  for (const [re, vals] of THEME_RULES) {
    if (re.test(name)) vals.forEach((v) => themes.add(v));
  }
  // Fallback: unmatched exams default to a broad general-aptitude classification.
  if (streams.size === 0) {
    streams.add("Commerce");
    streams.add("Humanities");
  }
  if (themes.size === 0) {
    themes.add("achiever");
    themes.add("structure");
  }
  const { category, color } = categoryFor(name);
  return {
    name,
    abbr,
    streams: [...streams],
    themes: [...themes],
    category,
    color,
    url: examSearchUrl(name, abbr),
  };
}

const EXAMS = RAW_EXAMS.map(classifyExam);

export { EXAMS, RAW_EXAMS, classifyExam };
