// 10 scenario templates per domain x 5 domains = 50 templates.
// Each has 5 options, one per theme in that domain. Expanded against
// SCENARIO_SETTINGS (30 settings) by the generator = 300 items/domain = 1500 total.
// {{setting}} gets substituted with a phrase from SCENARIO_SETTINGS.

const SCENARIO_TEMPLATES = [
  // ============ THINK: evidence / ideaspark / deepthink / chessplayer / visionary ============
  { domain: "Think", prompt: "{{setting}}, you're given an open-ended problem with no fixed approach. What's your first move?", options: [
    { theme: "evidence", text: "Research what's already proven to work, and build from solid facts." },
    { theme: "ideaspark", text: "Brainstorm a long list of unusual angles no one else would pick." },
    { theme: "deepthink", text: "Sit alone for a while and think it through before discussing it with anyone." },
    { theme: "chessplayer", text: "Map out the likely obstacles and a step-by-step plan before starting." },
    { theme: "visionary", text: "Pick a direction that connects to where things are heading, not just today." },
  ]},
  { domain: "Think", prompt: "{{setting}}, a friend asks for your honest take on a tricky decision. You:", options: [
    { theme: "evidence", text: "Ask them what evidence or past results they're basing it on." },
    { theme: "ideaspark", text: "Suggest a few options they haven't even considered." },
    { theme: "deepthink", text: "Tell them to give you time to actually think it through properly." },
    { theme: "chessplayer", text: "Walk them through what happens two or three steps after each choice." },
    { theme: "visionary", text: "Ask where they want to be years from now, and work backward from there." },
  ]},
  { domain: "Think", prompt: "{{setting}}, you hit a wall on a hard problem. What do you instinctively do?", options: [
    { theme: "evidence", text: "Re-check the facts you're sure of, and rule out the wrong paths." },
    { theme: "ideaspark", text: "Try an unconventional method even if it's not the usual way." },
    { theme: "deepthink", text: "Slow down and think in silence instead of rushing an answer." },
    { theme: "chessplayer", text: "Think about which approach carries the least risk given the time left." },
    { theme: "visionary", text: "Step back and think about the bigger picture the problem is part of." },
  ]},
  { domain: "Think", prompt: "{{setting}}, the group has to choose between two competing plans. You push for:", options: [
    { theme: "evidence", text: "Whichever plan has actual data or precedent behind it." },
    { theme: "ideaspark", text: "A third option nobody else has thought of yet." },
    { theme: "deepthink", text: "Taking more time before anyone commits to either plan." },
    { theme: "chessplayer", text: "Whichever plan has fewer ways it could go wrong." },
    { theme: "visionary", text: "Whichever plan sets things up better for the future, not just now." },
  ]},
  { domain: "Think", prompt: "{{setting}}, someone makes a confident claim that sounds a little off. You:", options: [
    { theme: "evidence", text: "Ask them directly how they know that's true." },
    { theme: "ideaspark", text: "Wonder out loud about other explanations they haven't mentioned." },
    { theme: "deepthink", text: "Stay quiet and turn it over in your head before reacting." },
    { theme: "chessplayer", text: "Consider what would happen if you acted on that claim and it turned out wrong." },
    { theme: "visionary", text: "Think about whether the claim will even matter a few years from now." },
  ]},
  { domain: "Think", prompt: "{{setting}}, you're asked to present your thinking to the whole group. You focus on:", options: [
    { theme: "evidence", text: "Laying out the facts and sources behind your conclusion." },
    { theme: "ideaspark", text: "The most original idea you came up with." },
    { theme: "deepthink", text: "The deeper reasoning most people skipped over." },
    { theme: "chessplayer", text: "The risks and trade-offs of each option." },
    { theme: "visionary", text: "Where this could lead if it's taken further." },
  ]},
  { domain: "Think", prompt: "{{setting}}, you have to make a call with incomplete information. You:", options: [
    { theme: "evidence", text: "Go with whatever the limited data actually supports." },
    { theme: "ideaspark", text: "Fill the gap with a creative guess worth testing." },
    { theme: "deepthink", text: "Take the extra time to reason it through carefully first." },
    { theme: "chessplayer", text: "Pick the option that's safest if you turn out to be wrong." },
    { theme: "visionary", text: "Choose based on which outcome you'd want years from now." },
  ]},
  { domain: "Think", prompt: "{{setting}}, two people disagree about the right approach. You naturally:", options: [
    { theme: "evidence", text: "Try to find out who actually has the facts on their side." },
    { theme: "ideaspark", text: "Suggest a completely different angle that sidesteps the disagreement." },
    { theme: "deepthink", text: "Need to sit with both views before forming your own opinion." },
    { theme: "chessplayer", text: "Think through what each approach risks if it fails." },
    { theme: "visionary", text: "Ask which approach fits where things are realistically headed." },
  ]},
  { domain: "Think", prompt: "{{setting}}, you're the one who has to explain why a plan didn't work. You focus on:", options: [
    { theme: "evidence", text: "What the actual numbers or outcomes show went wrong." },
    { theme: "ideaspark", text: "A genuinely different way to approach it next time." },
    { theme: "deepthink", text: "The underlying reason, not just the surface mistake." },
    { theme: "chessplayer", text: "Which warning signs were missed before it failed." },
    { theme: "visionary", text: "How this changes the long-term direction going forward." },
  ]},
  { domain: "Think", prompt: "{{setting}}, you have one free hour to prepare before things start. You spend it:", options: [
    { theme: "evidence", text: "Double-checking facts and details you'll need." },
    { theme: "ideaspark", text: "Letting your mind wander toward new angles." },
    { theme: "deepthink", text: "Thinking quietly instead of doing anything visible." },
    { theme: "chessplayer", text: "Running through what could go wrong and how to handle it." },
    { theme: "visionary", text: "Imagining how this connects to something bigger later on." },
  ]},

  // ============ DRIVE: achiever / laser / structure / ownership / fixer ============
  { domain: "Drive", prompt: "{{setting}}, you're handed a long list of tasks. What's your style?", options: [
    { theme: "achiever", text: "I want to finish as many as possible — momentum matters to me." },
    { theme: "laser", text: "I pick the most important one and stay on it until it's fully done." },
    { theme: "structure", text: "I build a clear schedule first, then follow it task by task." },
    { theme: "ownership", text: "I make sure I personally follow through, even on tasks that aren't 'mine.'" },
    { theme: "fixer", text: "I look for whichever task is most behind schedule and fix that first." },
  ]},
  { domain: "Drive", prompt: "{{setting}}, things start falling apart close to the deadline. You:", options: [
    { theme: "achiever", text: "Push hard to get something — anything — finished and submitted." },
    { theme: "laser", text: "Lock in on the single most critical part and ignore the rest." },
    { theme: "structure", text: "Quickly rebuild a step-by-step plan for the remaining time." },
    { theme: "ownership", text: "Take charge of making sure it gets done, even if it's not your part." },
    { theme: "fixer", text: "Diagnose exactly what went wrong and patch that specific issue." },
  ]},
  { domain: "Drive", prompt: "{{setting}}, what frustrates you most about how the group is working?", options: [
    { theme: "achiever", text: "People who talk a lot but don't actually produce anything." },
    { theme: "laser", text: "Constant interruptions that break your concentration." },
    { theme: "structure", text: "No plan, no timeline, just chaos." },
    { theme: "ownership", text: "People who don't take responsibility when something goes wrong." },
    { theme: "fixer", text: "Problems everyone notices but no one tries to actually solve." },
  ]},
  { domain: "Drive", prompt: "{{setting}}, you're given full freedom in how you spend your time. You:", options: [
    { theme: "achiever", text: "Set yourself a target so you have something concrete to finish." },
    { theme: "laser", text: "Pick one thing and go deep on it without switching tasks." },
    { theme: "structure", text: "Build yourself a loose schedule so the time doesn't slip away." },
    { theme: "ownership", text: "Use it to finish something you already promised someone." },
    { theme: "fixer", text: "Spend it fixing something that's been bothering you for a while." },
  ]},
  { domain: "Drive", prompt: "{{setting}}, your role hasn't been clearly assigned yet. You:", options: [
    { theme: "achiever", text: "Just start producing output so the group has something to react to." },
    { theme: "laser", text: "Claim the part that needs the most sustained focus." },
    { theme: "structure", text: "Suggest a clear division of roles before anyone starts." },
    { theme: "ownership", text: "Volunteer for whatever part is riskiest to leave unclaimed." },
    { theme: "fixer", text: "Look for whatever's already going wrong and take that on." },
  ]},
  { domain: "Drive", prompt: "{{setting}}, you finish your part early. What do you do next?", options: [
    { theme: "achiever", text: "Look for another task to finish — staying idle bothers you." },
    { theme: "laser", text: "Go back and refine your work further before moving on." },
    { theme: "structure", text: "Check the plan to see what's scheduled next." },
    { theme: "ownership", text: "Check in on whether the overall thing is actually on track." },
    { theme: "fixer", text: "Look around for something that's stuck or broken and help with it." },
  ]},
  { domain: "Drive", prompt: "{{setting}}, you're under real time pressure. Your instinct is to:", options: [
    { theme: "achiever", text: "Push through and just get it done, polish be damned." },
    { theme: "laser", text: "Block out everything else and focus on the one thing that matters most." },
    { theme: "structure", text: "Quickly re-prioritise based on a clear plan, not panic." },
    { theme: "ownership", text: "Make sure your commitment doesn't fall through, whatever it takes." },
    { theme: "fixer", text: "Triage — fix the most broken thing first, leave the rest." },
  ]},
  { domain: "Drive", prompt: "{{setting}}, a teammate drops out last-minute. You:", options: [
    { theme: "achiever", text: "Absorb their workload so the output doesn't suffer." },
    { theme: "laser", text: "Stay focused on your own part instead of getting distracted by the gap." },
    { theme: "structure", text: "Re-plan the whole timeline around the missing person." },
    { theme: "ownership", text: "Take personal responsibility for covering the gap." },
    { theme: "fixer", text: "Figure out exactly what's now broken and patch it directly." },
  ]},
  { domain: "Drive", prompt: "{{setting}}, you're asked what 'success' looks like for you here. You say:", options: [
    { theme: "achiever", text: "Getting it actually finished and delivered." },
    { theme: "laser", text: "Doing the one core thing really well, without distraction." },
    { theme: "structure", text: "Following through on the plan we set, start to finish." },
    { theme: "ownership", text: "Knowing I didn't let anyone down on my part of it." },
    { theme: "fixer", text: "Leaving things in better shape than I found them." },
  ]},
  { domain: "Drive", prompt: "{{setting}}, the original plan clearly isn't working anymore. You:", options: [
    { theme: "achiever", text: "Push to keep producing output even as the plan shifts." },
    { theme: "laser", text: "Stay locked onto your one task regardless of the chaos around it." },
    { theme: "structure", text: "Stop and rebuild a new plan before continuing." },
    { theme: "ownership", text: "Make sure someone is accountable for steering it back on track." },
    { theme: "fixer", text: "Jump straight to repairing whatever broke the plan in the first place." },
  ]},

  // ============ CONNECT: heartreader / grower / depthbond / peacemaker / welcomeall ============
  { domain: "Connect", prompt: "{{setting}}, a classmate seems off but hasn't said anything. You:", options: [
    { theme: "heartreader", text: "Notice immediately and check in on how they're really feeling." },
    { theme: "grower", text: "Think about how you could help them get back on track." },
    { theme: "depthbond", text: "Reach out privately, because you two are genuinely close." },
    { theme: "peacemaker", text: "Try to ease any tension in the group so it doesn't get worse." },
    { theme: "welcomeall", text: "Make sure they still feel included in whatever's happening." },
  ]},
  { domain: "Connect", prompt: "{{setting}}, what do you care about most in how people treat each other?", options: [
    { theme: "heartreader", text: "That people notice how others are really feeling." },
    { theme: "grower", text: "That people push each other to grow and improve." },
    { theme: "depthbond", text: "That the bonds formed are deep, not just casual." },
    { theme: "peacemaker", text: "That conflict gets resolved instead of left to fester." },
    { theme: "welcomeall", text: "That no one is made to feel like an outsider." },
  ]},
  { domain: "Connect", prompt: "{{setting}}, someone new joins the group mid-way through. Your reaction:", options: [
    { theme: "heartreader", text: "Pay attention to how they're feeling on their first day in." },
    { theme: "grower", text: "Look for ways to help them catch up faster." },
    { theme: "depthbond", text: "Wait to see if a real friendship forms naturally over time." },
    { theme: "peacemaker", text: "Make sure they're not caught in the middle of existing tension." },
    { theme: "welcomeall", text: "Go out of your way so they're not left out on day one." },
  ]},
  { domain: "Connect", prompt: "{{setting}}, two people you know start arguing nearby. You:", options: [
    { theme: "heartreader", text: "Notice the hurt underneath the argument before either of them says it." },
    { theme: "grower", text: "Think about what each of them needs to grow past this." },
    { theme: "depthbond", text: "Step in only for the one you're genuinely close to." },
    { theme: "peacemaker", text: "Try to help them find common ground." },
    { theme: "welcomeall", text: "Make sure the rest of the group doesn't end up picking sides." },
  ]},
  { domain: "Connect", prompt: "{{setting}}, a friend shares something vulnerable with you. You:", options: [
    { theme: "heartreader", text: "Focus completely on how they're feeling in that moment." },
    { theme: "grower", text: "Think about how to help them move forward from it." },
    { theme: "depthbond", text: "Feel honoured because this is the kind of trust you value most." },
    { theme: "peacemaker", text: "Help them see the situation calmly, without added drama." },
    { theme: "welcomeall", text: "Make sure they know they're not alone in feeling this way." },
  ]},
  { domain: "Connect", prompt: "{{setting}}, you notice the group dynamic feels slightly off. You:", options: [
    { theme: "heartreader", text: "Try to sense what's actually bothering people underneath." },
    { theme: "grower", text: "Look for who might need encouragement right now." },
    { theme: "depthbond", text: "Check in privately with the person you're closest to first." },
    { theme: "peacemaker", text: "Try to smooth things over before it turns into real conflict." },
    { theme: "welcomeall", text: "Check whether someone has been quietly excluded." },
  ]},
  { domain: "Connect", prompt: "{{setting}}, what would make you feel most fulfilled afterward?", options: [
    { theme: "heartreader", text: "Knowing you really understood how people felt throughout." },
    { theme: "grower", text: "Knowing you helped someone become a bit better at something." },
    { theme: "depthbond", text: "Knowing a relationship got deeper because of it." },
    { theme: "peacemaker", text: "Knowing you helped keep the peace when it mattered." },
    { theme: "welcomeall", text: "Knowing everyone felt like they belonged." },
  ]},
  { domain: "Connect", prompt: "{{setting}}, you're asked to pick a partner or small team. You choose based on:", options: [
    { theme: "heartreader", text: "Who you can read and connect with most easily." },
    { theme: "grower", text: "Who you think you could help improve the most." },
    { theme: "depthbond", text: "Whoever you already trust the most." },
    { theme: "peacemaker", text: "Whoever keeps the group calmest and most cooperative." },
    { theme: "welcomeall", text: "Whoever seems most likely to be left out otherwise." },
  ]},
  { domain: "Connect", prompt: "{{setting}}, someone admits they're struggling to keep up. You:", options: [
    { theme: "heartreader", text: "Acknowledge how hard that must feel before anything else." },
    { theme: "grower", text: "Offer to help them build the skill they're missing." },
    { theme: "depthbond", text: "Make time for a real one-on-one conversation about it." },
    { theme: "peacemaker", text: "Make sure no one else makes them feel worse about it." },
    { theme: "welcomeall", text: "Make sure they still feel like part of the group despite it." },
  ]},
  { domain: "Connect", prompt: "{{setting}}, you have to give someone difficult feedback. You:", options: [
    { theme: "heartreader", text: "Read the moment carefully so it lands gently." },
    { theme: "grower", text: "Frame it around how it'll help them grow." },
    { theme: "depthbond", text: "Only feel comfortable doing this with people you're close to." },
    { theme: "peacemaker", text: "Soften it so it doesn't create unnecessary conflict." },
    { theme: "welcomeall", text: "Make sure it doesn't make them feel excluded from the group." },
  ]},

  // ============ LEAD: igniter / stageowner / storyteller / connector / amplifier ============
  { domain: "Lead", prompt: "{{setting}}, the group has a great idea but no one is moving on it. You:", options: [
    { theme: "igniter", text: "Just start doing the first step yourself so it actually begins." },
    { theme: "stageowner", text: "Step up and start assigning roles and making calls." },
    { theme: "storyteller", text: "Explain the idea in a way that finally gets everyone on board." },
    { theme: "connector", text: "Bring in other people who could help make it happen." },
    { theme: "amplifier", text: "Push to make the idea sharper and more ambitious before starting." },
  ]},
  { domain: "Lead", prompt: "{{setting}}, what's your natural role in a discussion?", options: [
    { theme: "igniter", text: "The one who gets things actually moving." },
    { theme: "stageowner", text: "The one who ends up directing how it unfolds." },
    { theme: "storyteller", text: "The one whose explanation people remember afterward." },
    { theme: "connector", text: "The one who brings in other people's perspectives." },
    { theme: "amplifier", text: "The one who pushes everyone's points to be sharper." },
  ]},
  { domain: "Lead", prompt: "{{setting}}, you're asked to take the lead on short notice. Your instinct:", options: [
    { theme: "igniter", text: "Stop planning at some point and just get things moving." },
    { theme: "stageowner", text: "Take the lead role and make the final decisions yourself." },
    { theme: "storyteller", text: "Pitch it in a way that gets people genuinely excited." },
    { theme: "connector", text: "Pull in people from different groups to help." },
    { theme: "amplifier", text: "Take the basic idea and make it noticeably more impressive." },
  ]},
  { domain: "Lead", prompt: "{{setting}}, the energy in the room is flat. You:", options: [
    { theme: "igniter", text: "Just start doing something so momentum picks up." },
    { theme: "stageowner", text: "Take charge and direct people toward a clear next step." },
    { theme: "storyteller", text: "Tell it in a way that makes people care again." },
    { theme: "connector", text: "Bring in someone new whose energy might shift things." },
    { theme: "amplifier", text: "Raise the bar on what's being attempted to make it exciting again." },
  ]},
  { domain: "Lead", prompt: "{{setting}}, you disagree with the direction the group is taking. You:", options: [
    { theme: "igniter", text: "Just start doing it your way and let the results speak." },
    { theme: "stageowner", text: "Step in and redirect the group's decision firmly." },
    { theme: "storyteller", text: "Make the case for a different direction in a way people will actually hear." },
    { theme: "connector", text: "Bring in someone whose opinion the group will trust more." },
    { theme: "amplifier", text: "Push for a stronger, more ambitious version of either direction." },
  ]},
  { domain: "Lead", prompt: "{{setting}}, you need buy-in from people who don't report to you. You:", options: [
    { theme: "igniter", text: "Show momentum by already being in motion." },
    { theme: "stageowner", text: "Take ownership of the outcome so people trust your direction." },
    { theme: "storyteller", text: "Tell the story of why this matters in a way that resonates." },
    { theme: "connector", text: "Use your existing relationships to get people on side." },
    { theme: "amplifier", text: "Make the vision big enough that people want in." },
  ]},
  { domain: "Lead", prompt: "{{setting}}, things are going fine, but you sense untapped potential. You:", options: [
    { theme: "igniter", text: "Start a new initiative without waiting for permission." },
    { theme: "stageowner", text: "Take the lead in pushing things further." },
    { theme: "storyteller", text: "Paint a picture of what it could become." },
    { theme: "connector", text: "Bring in new people who could unlock that potential." },
    { theme: "amplifier", text: "Push everyone, including yourself, to aim higher." },
  ]},
  { domain: "Lead", prompt: "{{setting}}, you're the newest person in the room. You still:", options: [
    { theme: "igniter", text: "End up being the one who gets things started." },
    { theme: "stageowner", text: "Find yourself naturally taking the lead anyway." },
    { theme: "storyteller", text: "End up being the one explaining things clearly to others." },
    { theme: "connector", text: "End up introducing people who hadn't met before." },
    { theme: "amplifier", text: "Push for a better version of what's already being done." },
  ]},
  { domain: "Lead", prompt: "{{setting}}, your idea gets rejected at first. You:", options: [
    { theme: "igniter", text: "Start a small version of it anyway to prove it works." },
    { theme: "stageowner", text: "Push to be given the authority to try it properly." },
    { theme: "storyteller", text: "Re-pitch it with a story that lands better this time." },
    { theme: "connector", text: "Find an ally who can help get others on board." },
    { theme: "amplifier", text: "Come back with a bigger, more compelling version of it." },
  ]},
  { domain: "Lead", prompt: "{{setting}}, you have five minutes to convince a skeptical group. You:", options: [
    { theme: "igniter", text: "Show, don't tell — start doing it in front of them." },
    { theme: "stageowner", text: "Speak with the confidence of someone already in charge." },
    { theme: "storyteller", text: "Open with a story that makes them care immediately." },
    { theme: "connector", text: "Name someone they trust who's already on board." },
    { theme: "amplifier", text: "Make the upside sound as big and real as it actually is." },
  ]},

  // ============ GROW: growthseeker / collector / flowstate / conviction / legacy ============
  { domain: "Grow", prompt: "{{setting}}, you can choose how to spend the time. What pulls you most?", options: [
    { theme: "growthseeker", text: "Practicing a skill you're currently bad at, just to improve." },
    { theme: "collector", text: "Going deep into a topic you find interesting, just to learn more." },
    { theme: "flowstate", text: "Whatever comes up — you'll decide once you see how it goes." },
    { theme: "conviction", text: "A cause or issue you genuinely believe matters." },
    { theme: "legacy", text: "Something that builds toward a long-term goal you care about." },
  ]},
  { domain: "Grow", prompt: "{{setting}}, plans suddenly fall apart. You:", options: [
    { theme: "growthseeker", text: "Use the free time to work on something you're trying to get better at." },
    { theme: "collector", text: "Dive into something you'd bookmarked for later." },
    { theme: "flowstate", text: "Shrug, adjust, and figure out something else just as easily." },
    { theme: "conviction", text: "Spend the time on something that aligns with your values." },
    { theme: "legacy", text: "Use it to make progress on a goal that matters long-term." },
  ]},
  { domain: "Grow", prompt: "{{setting}}, what would genuinely disappoint you most looking back?", options: [
    { theme: "growthseeker", text: "Not having grown much from where you started." },
    { theme: "collector", text: "Not knowing as much as you wanted about things you cared about." },
    { theme: "flowstate", text: "Having been too rigid to adapt when things changed." },
    { theme: "conviction", text: "Having compromised on what you believe in." },
    { theme: "legacy", text: "Not having built or left behind anything that mattered." },
  ]},
  { domain: "Grow", prompt: "{{setting}}, you're offered an easier path or a harder one. You lean toward:", options: [
    { theme: "growthseeker", text: "The harder one, because you'll come out better for it." },
    { theme: "collector", text: "Whichever one teaches you more, regardless of difficulty." },
    { theme: "flowstate", text: "Whichever fits the situation best right now." },
    { theme: "conviction", text: "Whichever one is actually the right thing to do." },
    { theme: "legacy", text: "Whichever one matters more in the long run." },
  ]},
  { domain: "Grow", prompt: "{{setting}}, you fail at something you tried hard at. You:", options: [
    { theme: "growthseeker", text: "Focus on what you learned and how you'll improve." },
    { theme: "collector", text: "Go research why it happened in more depth." },
    { theme: "flowstate", text: "Adjust quickly and move on without much disruption." },
    { theme: "conviction", text: "Stay true to your approach if you still believe it was right." },
    { theme: "legacy", text: "Think about whether it still served the bigger goal." },
  ]},
  { domain: "Grow", prompt: "{{setting}}, someone challenges a belief you hold. You:", options: [
    { theme: "growthseeker", text: "Treat it as a chance to test and improve your thinking." },
    { theme: "collector", text: "Want to research more before responding properly." },
    { theme: "flowstate", text: "Stay open and adjust your view if their point is solid." },
    { theme: "conviction", text: "Hold your ground if you still believe you're right." },
    { theme: "legacy", text: "Think about what this means for the bigger picture you care about." },
  ]},
  { domain: "Grow", prompt: "{{setting}}, you're choosing between two long-term paths. You decide based on:", options: [
    { theme: "growthseeker", text: "Which one will stretch and develop you more." },
    { theme: "collector", text: "Which one lets you keep learning the most over time." },
    { theme: "flowstate", text: "Which one leaves you room to adapt as things change." },
    { theme: "conviction", text: "Which one fits your values best." },
    { theme: "legacy", text: "Which one leaves behind something that lasts." },
  ]},
  { domain: "Grow", prompt: "{{setting}}, you've been at this a while with no clear payoff yet. You:", options: [
    { theme: "growthseeker", text: "Keep going because you can feel yourself improving." },
    { theme: "collector", text: "Keep going because you're still learning something new." },
    { theme: "flowstate", text: "Stay flexible about whether to continue or pivot." },
    { theme: "conviction", text: "Keep going because you still believe it's the right thing to do." },
    { theme: "legacy", text: "Keep going because of what it'll mean later, not now." },
  ]},
  { domain: "Grow", prompt: "{{setting}}, a mentor asks what you actually want out of this. You say:", options: [
    { theme: "growthseeker", text: "To become noticeably better than I am right now." },
    { theme: "collector", text: "To understand it more deeply than I do today." },
    { theme: "flowstate", text: "To handle whatever comes up well, whatever that turns out to be." },
    { theme: "conviction", text: "To do it in a way I can stand behind." },
    { theme: "legacy", text: "To leave something behind that actually mattered." },
  ]},
  { domain: "Grow", prompt: "{{setting}}, you have to explain your motivation to someone skeptical. You say:", options: [
    { theme: "growthseeker", text: "I want to see how far I can actually push myself." },
    { theme: "collector", text: "I genuinely want to understand this properly." },
    { theme: "flowstate", text: "I'll figure it out as it unfolds — that's fine by me." },
    { theme: "conviction", text: "Because it's the right thing to do, full stop." },
    { theme: "legacy", text: "Because I want this to matter beyond just me." },
  ]},
];

export { SCENARIO_TEMPLATES };
