// UniTracko 25 talent themes, grouped into 5 student-relevant domains.
// Each theme: id (used as key everywhere else), name, domain, short description,
// a one-line "in practice" descriptor, a careerAngle (how this shows up in work),
// a growthTip (one thing to try this term), and the streams it most naturally fits.

const THEMES = [
  // ---------- Domain 1: THINK — how you process and create ideas ----------
  {
    id: "evidence",
    name: "Evidence",
    domain: "Think",
    icon: "\u{1F50E}",
    description: "You trust data and logic over assumptions. You like breaking a problem into parts before deciding anything.",
    inPractice: "You're the one who asks 'where's the proof?' before the group moves forward.",
    careerAngle: "Roles that reward this: research, data analysis, diagnostics, auditing, engineering — anywhere a wrong guess is expensive and being right matters more than being fast.",
    growthTip: "This term, practice stating your conclusion before you explain your reasoning — it trains you to lead with the answer, not just the proof.",
    streams: ["PCM", "PCMB", "Commerce"],
  },
  {
    id: "ideaspark",
    name: "IdeaSparker",
    domain: "Think",
    icon: "\u{1F4A1}",
    description: "New angles and possibilities come easily to you. You enjoy brainstorming and connecting unrelated ideas.",
    inPractice: "You're usually the one who says 'what if we tried it this way instead?'",
    careerAngle: "Roles that reward this: product design, advertising, R&D, entrepreneurship — anywhere the first idea in the room usually isn't the best one, and someone needs to generate more.",
    growthTip: "Keep an 'idea dump' note on your phone — half the value of this strength is lost if the ideas aren't written down before they're forgotten.",
    streams: ["Humanities", "PCMB", "Vocational"],
  },
  {
    id: "deepthink",
    name: "DeepThink",
    domain: "Think",
    icon: "\u{1F9D8}",
    description: "You like sitting alone with a hard idea and turning it over until it makes sense, rather than rushing to act.",
    inPractice: "You're comfortable with silence while you think something through fully.",
    careerAngle: "Roles that reward this: research, writing, strategy, law, philosophy — anywhere depth beats speed and the first answer usually isn't the best one.",
    growthTip: "Protect a fixed daily block of quiet, no-phone thinking time — this strength quietly weakens if every hour is filled with noise.",
    streams: ["PCM", "Humanities", "PCMB"],
  },
  {
    id: "chessplayer",
    name: "ChessPlayer",
    domain: "Think",
    icon: "\u{265F}",
    description: "You naturally think several steps ahead, weighing options before committing to a plan.",
    inPractice: "Before any group project starts, you've already mapped out how it could go wrong.",
    careerAngle: "Roles that reward this: strategy, finance, operations, competitive sports analysis, law — anywhere a wrong move three steps from now matters today.",
    growthTip: "Practice saying your second-best option out loud, not just your first — it forces you to show your reasoning, not just your conclusion.",
    streams: ["Commerce", "PCM", "Humanities"],
  },
  {
    id: "visionary",
    name: "Visionary",
    domain: "Think",
    icon: "\u{1F52E}",
    description: "You're energised by imagining what could exist in the future, even if it doesn't exist yet.",
    inPractice: "You talk about 'in 10 years' more than most people your age.",
    careerAngle: "Roles that reward this: entrepreneurship, design, policy, technology — anywhere someone needs to point at a future that doesn't exist yet and convince others to build toward it.",
    growthTip: "Pair every big-picture idea with one concrete next step — visionaries lose credibility fast if the future never connects to today.",
    streams: ["PCM", "Commerce", "Vocational"],
  },

  // ---------- Domain 2: DRIVE — how you execute and achieve ----------
  {
    id: "achiever",
    name: "Achiever",
    domain: "Drive",
    icon: "\u{1F3C1}",
    description: "You need to produce, finish, and tick things off. A day without progress feels wrong.",
    inPractice: "You're the one with every assignment submitted early, not at 11:58pm.",
    careerAngle: "Roles that reward this: sales, project delivery, entrepreneurship, competitive exams prep — anywhere consistent output matters more than occasional brilliance.",
    growthTip: "Watch for chasing quantity over quality — schedule one task a week where you deliberately go deeper instead of moving on fast.",
    streams: ["PCM", "PCB", "Commerce"],
  },
  {
    id: "laser",
    name: "Laser",
    domain: "Drive",
    icon: "\u{1F3AF}",
    description: "Once you pick a goal, distractions fade. You can focus on one thing for a long stretch.",
    inPractice: "You can study the same subject for 3 hours straight without checking your phone.",
    careerAngle: "Roles that reward this: deep technical work, research, competitive exam prep, craftsmanship — anywhere sustained single-task focus beats constant multitasking.",
    growthTip: "Use this strength deliberately on your hardest subject first, not your easiest — that's where uninterrupted focus pays off most.",
    streams: ["PCM", "PCB", "PCMB"],
  },
  {
    id: "structure",
    name: "Structure",
    domain: "Drive",
    icon: "\u{1F4CB}",
    description: "Routines, schedules, and order help you perform. Chaos drains you; a plan energises you.",
    inPractice: "You make a timetable before exams and actually follow most of it.",
    careerAngle: "Roles that reward this: operations, project management, accounting, logistics, administration — anywhere consistency and process prevent costly mistakes.",
    growthTip: "Build in deliberate buffer time in your schedule — structure breaks down fastest when there's zero room for things to run long.",
    streams: ["Commerce", "PCM", "Vocational"],
  },
  {
    id: "ownership",
    name: "Ownership",
    domain: "Drive",
    icon: "\u{1F91D}",
    description: "You take responsibility for outcomes, even ones that aren't fully your fault.",
    inPractice: "In group work, you're the one who makes sure the whole thing actually gets submitted.",
    careerAngle: "Roles that reward this: management, healthcare, entrepreneurship, any client-facing role — anywhere someone needs to be accountable when things don't go to plan.",
    growthTip: "Practice delegating one task you'd normally just do yourself — ownership without delegation eventually turns into burnout.",
    streams: ["PCB", "Commerce", "Humanities"],
  },
  {
    id: "fixer",
    name: "Fixer",
    domain: "Drive",
    icon: "\u{1F527}",
    description: "Broken or messy situations pull you in — you want to diagnose what's wrong and repair it.",
    inPractice: "When a group project is falling apart, you're the one who steps in and reorganises it.",
    careerAngle: "Roles that reward this: engineering, medicine, operations, IT support, crisis management — anywhere something breaks and someone needs to actually fix it, not just flag it.",
    growthTip: "Try getting involved before something breaks, not just after — your instinct for spotting problems early is as valuable as fixing them.",
    streams: ["PCM", "PCB", "Vocational"],
  },

  // ---------- Domain 3: CONNECT — how you understand people ----------
  {
    id: "heartreader",
    name: "HeartReader",
    domain: "Connect",
    icon: "\u{1F441}",
    description: "You pick up on what people are feeling before they say it, and it genuinely matters to you.",
    inPractice: "Friends come to you first when something's wrong, even before family.",
    careerAngle: "Roles that reward this: psychology, medicine, counselling, HR, teaching — anywhere reading what someone actually needs matters as much as what they ask for.",
    growthTip: "Set a boundary on how much emotional weight you carry for others — this strength runs out fast without recovery time built in.",
    streams: ["PCB", "Humanities", "PCMB"],
  },
  {
    id: "grower",
    name: "Grower",
    domain: "Connect",
    icon: "\u{1F33F}",
    description: "You notice potential in other people and enjoy helping them improve.",
    inPractice: "You end up unintentionally tutoring or coaching younger students or siblings.",
    careerAngle: "Roles that reward this: teaching, coaching, mentoring, HR/people development — anywhere someone's growth is the actual output, not just a side effect.",
    growthTip: "Try mentoring just one person consistently this term instead of giving scattered advice to many — depth beats breadth here.",
    streams: ["Humanities", "PCB", "PCMB"],
  },
  {
    id: "depthbond",
    name: "DepthBond",
    domain: "Connect",
    icon: "\u{1F49E}",
    description: "You prefer a few deep friendships over a wide social circle, and invest heavily in them.",
    inPractice: "You have 2-3 friends you'd trust with anything, rather than 30 acquaintances.",
    careerAngle: "Roles that reward this: counselling, account management, healthcare, any long-term client or patient relationship — anywhere trust built over time outperforms a wide shallow network.",
    growthTip: "Don't mistake this for shyness in group settings — practice contributing in larger groups even when it doesn't come naturally.",
    streams: ["Humanities", "PCB", "PCMB"],
  },
  {
    id: "peacemaker",
    name: "Peacemaker",
    domain: "Connect",
    icon: "\u{1F54A}",
    description: "You instinctively look for common ground and de-escalate tension in groups.",
    inPractice: "When two friends argue, you're the one who ends up mediating.",
    careerAngle: "Roles that reward this: law (mediation/arbitration), diplomacy, HR, conflict resolution, customer service leadership — anywhere two sides need to be brought to an actual agreement.",
    growthTip: "Notice when keeping the peace means avoiding a needed disagreement — practice raising the hard point once before smoothing things over.",
    streams: ["Humanities", "Commerce", "PCB"],
  },
  {
    id: "welcomeall",
    name: "WelcomeAll",
    domain: "Connect",
    icon: "\u{1F917}",
    description: "You make sure no one is left out — new students, quiet classmates, anyone on the edge of the group.",
    inPractice: "You're the one who sits next to the new kid on their first day.",
    careerAngle: "Roles that reward this: community work, hospitality, HR/DEI roles, event organising — anywhere making people feel included is the actual job, not a nice extra.",
    growthTip: "This strength shows up most when it's least convenient — notice the moments you're tempted to skip including someone, and don't.",
    streams: ["Humanities", "PCB", "Vocational"],
  },

  // ---------- Domain 4: LEAD — how you influence others ----------
  {
    id: "igniter",
    name: "Igniter",
    domain: "Lead",
    icon: "\u{1F680}",
    description: "You turn ideas into motion. Talk doesn't satisfy you — you want the thing actually started.",
    inPractice: "You're the one who says 'let's just start' while others are still debating.",
    careerAngle: "Roles that reward this: entrepreneurship, startups, sales, event organising — anywhere momentum matters more than a perfect plan.",
    growthTip: "Before you start the next thing, finish the last one — igniters are prone to starting five things and finishing two.",
    streams: ["Commerce", "PCM", "Vocational"],
  },
  {
    id: "stageowner",
    name: "StageOwner",
    domain: "Lead",
    icon: "\u{1F451}",
    description: "You're comfortable taking charge of a room and making decisions when no one else will.",
    inPractice: "In a leaderless group, you become the leader within five minutes, without trying to.",
    careerAngle: "Roles that reward this: management, defence services, entrepreneurship, politics — anywhere a group needs someone to actually decide, not just discuss.",
    growthTip: "Practice asking for input before deciding, not just after — natural leaders can accidentally crowd out quieter voices.",
    streams: ["Commerce", "Humanities", "PCM"],
  },
  {
    id: "storyteller",
    name: "Storyteller",
    domain: "Lead",
    icon: "\u{1F3A4}",
    description: "You explain things in ways that stick — through stories, examples, and clear language.",
    inPractice: "You're the one classmates ask to re-explain what the teacher just said.",
    careerAngle: "Roles that reward this: journalism, marketing, teaching, law (advocacy), content creation — anywhere being understood matters as much as being right.",
    growthTip: "Practice the same explanation in one sentence and then in five — knowing when to compress and when to expand is the real skill.",
    streams: ["Humanities", "Commerce", "PCMB"],
  },
  {
    id: "connector",
    name: "Connector",
    domain: "Lead",
    icon: "\u{1F517}",
    description: "You build rapport with almost anyone, quickly, and enjoy widening your network.",
    inPractice: "You somehow know someone in every other class or club.",
    careerAngle: "Roles that reward this: sales, PR, business development, event/community management — anywhere who you know becomes part of what you can get done.",
    growthTip: "Follow up with people after the first good conversation — connectors often meet a lot of people but forget to maintain the bridge.",
    streams: ["Commerce", "Humanities", "Vocational"],
  },
  {
    id: "amplifier",
    name: "Amplifier",
    domain: "Lead",
    icon: "\u{1F4C8}",
    description: "You take something that's already good and push it to be excellent — for yourself and others.",
    inPractice: "You're the one who says 'this is fine, but it could be way better' — and means it well.",
    careerAngle: "Roles that reward this: editing, coaching, quality/product management, performance consulting — anywhere good needs to become great, not just acceptable.",
    growthTip: "Practice saying what's already working before what needs improving — amplifiers can come across as critical if they skip this step.",
    streams: ["Commerce", "PCM", "PCMB"],
  },

  // ---------- Domain 5: GROW — how you learn and find meaning ----------
  {
    id: "growthseeker",
    name: "GrowthSeeker",
    domain: "Grow",
    icon: "\u{1F331}",
    description: "The process of getting better at something excites you more than the result itself.",
    inPractice: "You'd rather struggle through a hard topic than get an easy A in a boring one.",
    careerAngle: "Roles that reward this: any steep-learning-curve field — tech, medicine, research, competitive sport — anywhere the job keeps getting harder on purpose.",
    growthTip: "Pick one skill this term that has nothing to do with grades — this strength needs room to operate outside pure achievement.",
    streams: ["PCM", "PCB", "Humanities"],
  },
  {
    id: "collector",
    name: "Collector",
    domain: "Grow",
    icon: "\u{1F4DA}",
    description: "You gather information, facts, and resources — your notes and bookmarks are never-ending.",
    inPractice: "You have saved articles and videos 'for later' that genuinely number in the hundreds.",
    careerAngle: "Roles that reward this: research, journalism, library/information science, analytics — anywhere knowing more than everyone else in the room is the advantage.",
    growthTip: "Schedule time to actually revisit what you've saved — collectors gather a lot of value that never gets used if it's never reopened.",
    streams: ["Humanities", "PCM", "Commerce"],
  },
  {
    id: "flowstate",
    name: "FlowState",
    domain: "Grow",
    icon: "\u{1F30A}",
    description: "You adjust quickly when plans change and stay productive even when things are uncertain.",
    inPractice: "A cancelled class or last-minute change doesn't throw off your whole day.",
    careerAngle: "Roles that reward this: startups, emergency services, journalism, event management — anywhere the plan changes constantly and adapting fast is the job.",
    growthTip: "Pair your adaptability with one fixed daily anchor (like a set wake time) — total flexibility everywhere can drift into no structure at all.",
    streams: ["Vocational", "PCB", "Commerce"],
  },
  {
    id: "conviction",
    name: "Conviction",
    domain: "Grow",
    icon: "\u{2696}",
    description: "You have a strong, stable sense of right and wrong that guides your decisions even under pressure.",
    inPractice: "You'll say the unpopular true thing in a group even if it costs you socially.",
    careerAngle: "Roles that reward this: law, journalism, public service, ethics/compliance — anywhere holding a line matters more than being popular.",
    growthTip: "Practice separating 'I disagree' from 'you're wrong' in conversation — conviction lands better when it doesn't sound like judgment.",
    streams: ["Humanities", "PCB", "PCMB"],
  },
  {
    id: "legacy",
    name: "Legacy",
    domain: "Grow",
    icon: "\u{1F3F0}",
    description: "You want your work to matter beyond yourself — to leave something behind that outlasts the moment.",
    inPractice: "You think about how you'll be remembered more than most people your age do.",
    careerAngle: "Roles that reward this: public service, education, research, founding/building organisations — anywhere the timeline of impact is measured in years, not weeks.",
    growthTip: "Balance long-term thinking with one small visible win this month — legacy-minded people can underrate the value of short-term progress.",
    streams: ["Humanities", "PCB", "PCM"],
  },
];

const DOMAINS = [
  { id: "Think", name: "Think", tagline: "How you process and create ideas", color: "#4f46e5", icon: "\u{1F9E0}" },
  { id: "Drive", name: "Drive", tagline: "How you execute and achieve", color: "#ea580c", icon: "\u{1F525}" },
  { id: "Connect", name: "Connect", tagline: "How you understand people", color: "#e11d48", icon: "\u{1F49E}" },
  { id: "Lead", name: "Lead", tagline: "How you influence others", color: "#7c3aed", icon: "\u{1F3AF}" },
  { id: "Grow", name: "Grow", tagline: "How you learn and find meaning", color: "#16a34a", icon: "\u{1F331}" },
];

const STREAMS = ["PCM", "PCB", "PCMB", "Commerce", "Humanities", "Vocational"];

export { THEMES, DOMAINS, STREAMS };
